import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Sidebar from "./components/SideBar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} font-LoraIttalic font-medium bg-backgroundPrimary text-text flex dark`}
      >
        <Sidebar />
        <main className="fixMargin w-full">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
